Repository LoliGothick/mitama-cpp-result, pull requests merged in 2020-12, with the labels that each got.

#72 Support void for mitama::result
  include/mitama/result/detail/fwd.hpp
  include/mitama/result/result.hpp
  test/result_tests.cpp
Labels: enhancement

#79 Avoid double evaluation in the MITAMA_TRY macro
  include/mitama/result/result.hpp
  test/CMakeLists.txt
  test/result_tests.cpp
Labels: refactor

#80 Feature/renovate docs
  .github/workflows/deploy-docs.yml
  .github/workflows/full-test.yml
  .gitignore
  README.md
  docs/config.toml
  docs/docs/README.md
  docs/docs/cppmap_styles.css
  docs/docs/mathjaxhelper.js
  docs/docs/maybe/APIs.md
  docs/docs/maybe/_Internal/comparisons.todo
  docs/docs/maybe/comparisons.md
  docs/docs/maybe/intro.md
  docs/docs/maybe/metafunctions.md
  docs/docs/maybe/special_members.md
  docs/docs/result/APIs.md
  docs/docs/result/CHANGELOG.md
  docs/docs/result/comparisons.md
  docs/docs/result/intro.md
  docs/docs/result/metafunctions.md
  docs/docs/result/special_members.md
  docs/docs/style.css
  docs/mkdocs.yml
  docs/poetry.lock
  docs/pyproject.toml
Labels: CI, document, help wanted, refactor

#74 Add CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: document, pending
